# Test how intuit-oauth library works
import os
os.chdir(r'C:\Users\jovis\.openclaw\workspace\bookkeepr')

from dotenv import load_dotenv
load_dotenv()

from intuitlib.client import AuthClient
from intuitlib.enums import Scopes

# Create auth client
auth_client = AuthClient(
    client_id=os.getenv('INTUIT_CLIENT_ID'),
    client_secret=os.getenv('INTUIT_CLIENT_SECRET'),
    environment='sandbox',
    redirect_uri='http://localhost:5000/auth/callback'
)

# Get scopes
scopes = [Scopes.ACCOUNTING, Scopes.OPENID, Scopes.PROFILE, Scopes.EMAIL]

# Generate auth URL
auth_url = auth_client.get_authorization_url(scopes)

print("Auth URL generated by intuit-oauth:")
print(auth_url)
print()
print("State token generated:", auth_client.state_token if hasattr(auth_client, 'state_token') else "Not stored")
print()
print("Attributes of auth_client:")
for attr in dir(auth_client):
    if not attr.startswith('_'):
        print(f"  {attr}")
